// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU-heKDqfImXDERnJBjDhjkljZHSKkll0',
    appId: '1:615480465607:web:1e78c1cd5855307c2b46e2',
    messagingSenderId: '615480465607',
    projectId: 'nexforce-90202',
    authDomain: 'nexforce-90202.firebaseapp.com',
    storageBucket: 'nexforce-90202.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1t81pg4csi_wvK1vIsZ3MJCWIEAFv1V0',
    appId: '1:615480465607:android:fae569ee19c0fdb92b46e2',
    messagingSenderId: '615480465607',
    projectId: 'nexforce-90202',
    storageBucket: 'nexforce-90202.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn5XYFxkU6R8mX-aqyKhODmuq67qufquk',
    appId: '1:615480465607:ios:ed64de43318fb69c2b46e2',
    messagingSenderId: '615480465607',
    projectId: 'nexforce-90202',
    storageBucket: 'nexforce-90202.appspot.com',
    iosBundleId: 'com.example.nex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn5XYFxkU6R8mX-aqyKhODmuq67qufquk',
    appId: '1:615480465607:ios:ed64de43318fb69c2b46e2',
    messagingSenderId: '615480465607',
    projectId: 'nexforce-90202',
    storageBucket: 'nexforce-90202.appspot.com',
    iosBundleId: 'com.example.nex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU-heKDqfImXDERnJBjDhjkljZHSKkll0',
    appId: '1:615480465607:web:7de61abf7edc96b92b46e2',
    messagingSenderId: '615480465607',
    projectId: 'nexforce-90202',
    authDomain: 'nexforce-90202.firebaseapp.com',
    storageBucket: 'nexforce-90202.appspot.com',
  );
}
